### ISSUE TITLE
Move Camuda 8.6 Docker Compose from camunda/camunda-platform to this repo

### ISSUE THREAD

**Issue by aabouzaid** [camunda/camunda-distribution#2]
Move Camuda 8.6 Docker Compose from [camunda/camunda-platform](https://github.com/camunda/camunda-platform) to this.

```[tasklist]
### Tasks
- [ ] Move it to the same dir `docker-compose/camunda-8.6`.
- [ ] Ensure Docker Compose works locally as expected.
- [ ] Ensure the related GitHub Actions workflows are moved to this repo and work as expected.
```

**Comment by Aml286** [comment]
Kindly assign this task to me
