### ISSUE TITLE
Move Camuda 8.5 Docker Compose from camunda/camunda-platform to this repo

### ISSUE THREAD

**Issue by aabouzaid** [camunda/camunda-distribution#3]
Move Camuda 8.5 Docker Compose from [camunda/camunda-platform](https://github.com/camunda/camunda-platform) to this.

```[tasklist]
### Tasks
- [ ] Move it from the camunda/camunda-platform branch [stable/8.5](https://github.com/camunda/camunda-platform/tree/stable/8.5) the  dir `docker-compose/camunda-8.5`.
- [ ] Ensure Docker Compose works locally as expected.
- [ ] Ensure the related GitHub Actions workflows are moved to this repo and work as expected.
```

**Comment by EzzOps** [comment]
@aabouzaid could this task be assigned to me, I will work on it

**Comment by EzzOps** [comment]
@aabouzaid
need your advice please

I got this error

"unauthorized to access repository: web-modeler-ee/modeler-restapi" with docker-compose-web-modeler.yaml

because I don't have the correct credentials for the private register, so I use my dockerhub registry 

and the rest of the docker-compose works correctly
