### ISSUE TITLE
Move Camuda Docker Compose from camunda/camunda-platform to this repo

### ISSUE THREAD

**Issue by aabouzaid** [camunda/camunda-distribution#4]
Move Camuda 8.4 Docker Compose from [camunda/camunda-platform](https://github.com/camunda/camunda-platform) to this.

```[tasklist]
### Tasks
- [ ] Move it from the `camunda/camunda-platform` all versions the dir `docker-compose/camunda-*`
- [ ] Ensure Docker Compose works locally as expected.
- [ ] https://github.com/camunda/camunda-distribution/pull/11
```

**Comment by taha-adel** [comment]
I'd like to work on this one, @aabouzaid.

Should I include `docker-compose-web-modeler.yaml` and its associated workflows in this movement? It has private registry images and require credentials for authentication.

**Comment by aabouzaid** [comment]
@taha-adel Yeah, I've realized that there will be many issues with testing the private repos.
So I will take care of moving all versions. Please pick up another task from #1
