### ISSUE TITLE
Move Camuda 8.3 Docker Compose from camunda/camunda-platform to this repo

### ISSUE THREAD

**Issue by aabouzaid** [camunda/camunda-distribution#5]
Move Camuda 8.3 Docker Compose from [camunda/camunda-platform](https://github.com/camunda/camunda-platform) to this.

```[tasklist]
### Tasks
- [ ] Move it from the `camunda/camunda-platform` branch [stable/8.3](https://github.com/camunda/camunda-platform/tree/stable/8.3) the dir `docker-compose/camunda-8.3`.
- [ ] Ensure Docker Compose works locally as expected.
- [ ] Ensure the related GitHub Actions workflows are moved to this repo and work as expected.
```

**Comment by Dhruvnotfound** [comment]
hey i would love to work on this but i noticed there is no `docker-compose/camunda-8.3` in the` stable/8.3` branch of `camunda/camunda-platform`

**Comment by aabouzaid** [comment]
@Dhruvnotfound Thanks for your interest :raised_hands: 

The files are in the root of the `stable/8.3` branch of `camunda/camunda-platform`, and they should be moved to `docker-compose/camunda-8.3` dir in the current repo [camunda/camunda-distribution](https://github.com/camunda/camunda-distribution).

**Comment by Dhruvnotfound** [comment]
@aabouzaid 

Hey, when I am trying to run `docker-compose-web-modeler.yaml` locally, I am getting the following error:
``` ✘ modeler-restapi Error
✘ modeler-webapp Error
✘ modeler-websockets Error
Error response from daemon: unauthorized: unauthorized to access repository: web-modeler-ee/modeler-restapi, action: pull: unauthorized to access repository: web-modeler-ee/modeler-restapi, action: pull
```

similarly when checking the related GitHub Actions workflows it cant login to the private registry which is making me unable to test them.
its giving the following error message `Error: Cannot perform an interactive login from a non TTY device`
